apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.flaskApp.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.flaskApp.port }}
      targetPort: {{ .Values.flaskApp.port }}
  type: LoadBalancer
