apiVersion: v1
kind: Service
metadata:
  name: python-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.pythonServer.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.pythonServer.port }}
      targetPort: {{ .Values.pythonServer.port }}
  type: ClusterIP
