kind: Deployment
apiVersion: apps/v1
metadata:
  name: python-server
  namespace: proj-ns
  labels:
    app: python-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-server
  template:
    metadata:
      labels:
        app: python-server
    spec:
      containers:
        - name: python-server-container
          image: py-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
